### PR TITLE
js editors

### PR DESCRIPTION
**Pull request by joshlangner**
not a comprehensive list - could probably use more suggestions

### CODE REVIEW

**Comment by thvd** [comment]
Can you add Webstorm (PhpStorm) and Brackets to the list?

**Comment by steveax** [comment]
Probably best to add an "Other" option with a text field for entry. (and what, no love for BBEdit?)

**Comment by Deraen** [comment]
Vim and Emacs should be separate options as they differ a lot.
And more importantly, users of either will be angry if their favorite editor is associated with the "enemy" :smirk:

**Comment by keithn** [comment]
and visual studio....

**Comment by Raynos** [comment]
Add cloud9 and light table.

**Comment by rlidwka** [comment]
s/vi/vim/g

**Pull request merged**
