### PR TITLE
Adding questions on IE, ES6 and adding options for browersify and Volo

### PR DESCRIPTION
**Pull request by jjgonecrypto**
**new questions**
- added minimum version of IE question
- added usage of ES6 features

**added to existing**
- added CommonJS with browserify options
- added Volo to client side package management options

### CODE REVIEW

**Comment by bmeck** [comment]
+1 for ES6 Features, but maybe an option about transpilers like [facebook/regenerator](http://facebook.github.io/regenerator/) or [square/es6-arrow-function](https://github.com/square/es6-arrow-function)

**Comment by angelyordanov** [comment]
You can't use CommonJS modules on the client side without Browserify.

So instead of two options:
- CommonJS
- CommonJS with Browserify

It should be just one:
- CommonJS (with Browserify)

I guess that is what @alexyoung has in mind.

**Comment by jjgonecrypto** [comment]
It's JS @angelyordanov, you can do anything. What's the say people aren't appending their files with? 

```
if (typeof window !== 'undefined') window.XYZ = module.exports; 
```

or any other variant. Personally I'm curious if they are using the browserify option or cooking up their own thing.

**Comment by angelyordanov** [comment]
You have a point. I've done that for some edge cases but can't imagine someone using that in production.

**Comment by jjgonecrypto** [comment]
For the sake of a succinct survey I'll capitulate on this point.

**Pull request merged**
